import { AchievementDefinition } from '@/types/achievement';

export const ACHIEVEMENTS: AchievementDefinition[] = [
  {
    id: 'speed_100',
    title: 'Triple Digits',
    description: 'Hit 100 km/h on a trip',
    category: 'speed',
    icon: 'gauge',
    threshold: 100,
    unit: 'km/h',
  },

  {
    id: 'distance_first',
    title: 'First Drive',
    description: 'Complete your first trip',
    category: 'distance',
    icon: 'map-pin',
    threshold: 1,
  },
  {
    id: 'distance_100',
    title: 'Road Warrior',
    description: 'Drive 100 km total',
    category: 'distance',
    icon: 'route',
    threshold: 100,
    unit: 'km',
  },
  {
    id: 'distance_1000',
    title: 'Cross Country',
    description: 'Drive 1,000 km total',
    category: 'distance',
    icon: 'map',
    threshold: 1000,
    unit: 'km',
  },
  {
    id: 'distance_10000',
    title: 'Around the World',
    description: 'Drive 10,000 km total',
    category: 'distance',
    icon: 'globe',
    threshold: 10000,
    unit: 'km',
  },
  {
    id: 'distance_single_200',
    title: 'Long Hauler',
    description: 'Drive 200+ km in a single trip',
    category: 'distance',
    icon: 'route',
    threshold: 200,
    unit: 'km',
  },

  {
    id: 'trips_5',
    title: 'Getting Started',
    description: 'Complete 5 trips',
    category: 'trips',
    icon: 'flag',
    threshold: 5,
  },
  {
    id: 'trips_25',
    title: 'Regular Driver',
    description: 'Complete 25 trips',
    category: 'trips',
    icon: 'repeat',
    threshold: 25,
  },
  {
    id: 'trips_100',
    title: 'Road Veteran',
    description: 'Complete 100 trips',
    category: 'trips',
    icon: 'award',
    threshold: 100,
  },
  {
    id: 'trips_500',
    title: 'Unstoppable',
    description: 'Complete 500 trips',
    category: 'trips',
    icon: 'infinity',
    threshold: 500,
  },

  {
    id: 'streak_3',
    title: 'On a Roll',
    description: 'Maintain a 3-day driving streak',
    category: 'streak',
    icon: 'flame',
    threshold: 3,
  },
  {
    id: 'streak_7',
    title: 'Weekly Warrior',
    description: 'Maintain a 7-day driving streak',
    category: 'streak',
    icon: 'flame',
    threshold: 7,
  },
  {
    id: 'streak_30',
    title: 'Monthly Machine',
    description: 'Maintain a 30-day driving streak',
    category: 'streak',
    icon: 'flame',
    threshold: 30,
  },

  {
    id: 'social_follow_5',
    title: 'Networker',
    description: 'Follow 5 drivers',
    category: 'social',
    icon: 'users',
    threshold: 5,
  },
  {
    id: 'social_follow_25',
    title: 'Social Butterfly',
    description: 'Follow 25 drivers',
    category: 'social',
    icon: 'users',
    threshold: 25,
  },
  {
    id: 'social_followers_10',
    title: 'Popular',
    description: 'Get 10 followers',
    category: 'social',
    icon: 'star',
    threshold: 10,
  },
  {
    id: 'social_followers_50',
    title: 'Influencer',
    description: 'Get 50 followers',
    category: 'social',
    icon: 'star',
    threshold: 50,
  },

  {
    id: 'perf_gforce',
    title: 'G-Force Master',
    description: 'Experience 1.0 G-Force in a trip',
    category: 'performance',
    icon: 'zap',
    threshold: 1.0,
    unit: 'G',
  },
  {
    id: 'perf_corners_50',
    title: 'Corner King',
    description: 'Take 50 corners in a single trip',
    category: 'performance',
    icon: 'corner-down-right',
    threshold: 50,
  },
  {
    id: 'perf_corners_100',
    title: 'Apex Hunter',
    description: 'Take 100 corners in a single trip',
    category: 'performance',
    icon: 'corner-down-right',
    threshold: 100,
  },
  {
    id: 'perf_quick_launch',
    title: 'Quick Launch',
    description: '0-100 km/h in under 6 seconds',
    category: 'performance',
    icon: 'rocket',
    threshold: 6,
  },
  {
    id: 'perf_night_owl',
    title: 'Night Owl',
    description: 'Complete a trip after midnight',
    category: 'performance',
    icon: 'moon',
    threshold: 1,
  },
  {
    id: 'perf_marathon',
    title: 'Marathon Driver',
    description: 'Drive for 2+ hours in a single trip',
    category: 'performance',
    icon: 'clock',
    threshold: 7200,
    unit: 'sec',
  },
];

export const ACHIEVEMENT_CATEGORIES: { key: string; label: string; icon: string }[] = [
  { key: 'speed', label: 'Speed', icon: 'gauge' },
  { key: 'distance', label: 'Distance', icon: 'route' },
  { key: 'trips', label: 'Trips', icon: 'flag' },
  { key: 'streak', label: 'Streak', icon: 'flame' },
  { key: 'social', label: 'Social', icon: 'users' },
  { key: 'performance', label: 'Performance', icon: 'zap' },
];
