export interface Country {
  code: string;
  name: string;
  flag: string;
  cities: string[];
}

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫', cities: ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif', 'Jalalabad'] },
  { code: 'AL', name: 'Albania', flag: '🇦🇱', cities: ['Tirana', 'Durrës', 'Vlorë', 'Shkodër', 'Elbasan'] },
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿', cities: ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Blida'] },
  { code: 'AD', name: 'Andorra', flag: '🇦🇩', cities: ['Andorra la Vella', 'Escaldes-Engordany', 'Encamp', 'Sant Julià de Lòria'] },
  { code: 'AO', name: 'Angola', flag: '🇦🇴', cities: ['Luanda', 'Huambo', 'Lobito', 'Benguela', 'Lubango'] },
  { code: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬', cities: ["Saint John's", 'All Saints', 'Liberta', 'Potters Village'] },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷', cities: ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'La Plata', 'Mar del Plata', 'San Miguel de Tucumán'] },
  { code: 'AM', name: 'Armenia', flag: '🇦🇲', cities: ['Yerevan', 'Gyumri', 'Vanadzor', 'Vagharshapat', 'Abovyan'] },
  { code: 'AU', name: 'Australia', flag: '🇦🇺', cities: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Canberra', 'Newcastle', 'Hobart'] },
  { code: 'AT', name: 'Austria', flag: '🇦🇹', cities: ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck', 'Klagenfurt'] },
  { code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿', cities: ['Baku', 'Ganja', 'Sumqayit', 'Mingachevir', 'Lankaran'] },
  { code: 'BS', name: 'Bahamas', flag: '🇧🇸', cities: ['Nassau', 'Freeport', 'West End', 'Coopers Town', 'Marsh Harbour'] },
  { code: 'BH', name: 'Bahrain', flag: '🇧🇭', cities: ['Manama', 'Riffa', 'Muharraq', 'Hamad Town', 'Isa Town'] },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', cities: ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi', 'Sylhet', 'Comilla'] },
  { code: 'BB', name: 'Barbados', flag: '🇧🇧', cities: ['Bridgetown', 'Speightstown', 'Oistins', 'Bathsheba', 'Holetown'] },
  { code: 'BY', name: 'Belarus', flag: '🇧🇾', cities: ['Minsk', 'Gomel', 'Mogilev', 'Vitebsk', 'Grodno', 'Brest'] },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪', cities: ['Brussels', 'Antwerp', 'Ghent', 'Charleroi', 'Liège', 'Bruges', 'Namur'] },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿', cities: ['Belize City', 'San Ignacio', 'Belmopan', 'Orange Walk', 'Dangriga'] },
  { code: 'BJ', name: 'Benin', flag: '🇧🇯', cities: ['Cotonou', 'Porto-Novo', 'Parakou', 'Djougou', 'Bohicon'] },
  { code: 'BT', name: 'Bhutan', flag: '🇧🇹', cities: ['Thimphu', 'Phuntsholing', 'Paro', 'Punakha', 'Wangdue Phodrang'] },
  { code: 'BO', name: 'Bolivia', flag: '🇧🇴', cities: ['La Paz', 'Santa Cruz', 'Cochabamba', 'Sucre', 'Oruro', 'Tarija'] },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦', cities: ['Sarajevo', 'Banja Luka', 'Tuzla', 'Zenica', 'Mostar', 'Bijeljina'] },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼', cities: ['Gaborone', 'Francistown', 'Molepolole', 'Maun', 'Serowe'] },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷', cities: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Porto Alegre'] },
  { code: 'BN', name: 'Brunei', flag: '🇧🇳', cities: ['Bandar Seri Begawan', 'Kuala Belait', 'Seria', 'Tutong', 'Bangar'] },
  { code: 'BG', name: 'Bulgaria', flag: '🇧🇬', cities: ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Ruse', 'Stara Zagora'] },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', cities: ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Ouahigouya', 'Banfora'] },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮', cities: ['Bujumbura', 'Gitega', 'Muyinga', 'Ngozi', 'Ruyigi'] },
  { code: 'CV', name: 'Cabo Verde', flag: '🇨🇻', cities: ['Praia', 'Mindelo', 'Santa Maria', 'Espargos', 'Assomada'] },
  { code: 'KH', name: 'Cambodia', flag: '🇰🇭', cities: ['Phnom Penh', 'Siem Reap', 'Battambang', 'Sihanoukville', 'Kampong Cham'] },
  { code: 'CM', name: 'Cameroon', flag: '🇨🇲', cities: ['Douala', 'Yaoundé', 'Bamenda', 'Bafoussam', 'Garoua'] },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', cities: ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Quebec City', 'Hamilton', 'Halifax'] },
  { code: 'CF', name: 'Central African Republic', flag: '🇨🇫', cities: ['Bangui', 'Bimbo', 'Berbérati', 'Carnot', 'Bambari'] },
  { code: 'TD', name: 'Chad', flag: '🇹🇩', cities: ["N'Djamena", 'Moundou', 'Sarh', 'Abéché', 'Kélo'] },
  { code: 'CL', name: 'Chile', flag: '🇨🇱', cities: ['Santiago', 'Valparaíso', 'Concepción', 'La Serena', 'Antofagasta', 'Temuco', 'Viña del Mar'] },
  { code: 'CN', name: 'China', flag: '🇨🇳', cities: ['Shanghai', 'Beijing', 'Guangzhou', 'Shenzhen', 'Chengdu', 'Hangzhou', 'Wuhan', 'Xian', 'Nanjing', 'Chongqing', 'Hong Kong'] },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴', cities: ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena', 'Bucaramanga', 'Santa Marta'] },
  { code: 'KM', name: 'Comoros', flag: '🇰🇲', cities: ['Moroni', 'Mutsamudu', 'Fomboni', 'Domoni', 'Tsimbeo'] },
  { code: 'CG', name: 'Congo', flag: '🇨🇬', cities: ['Brazzaville', 'Pointe-Noire', 'Dolisie', 'Nkayi', 'Owando'] },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', cities: ['San José', 'Limón', 'Alajuela', 'Heredia', 'Cartago', 'Liberia'] },
  { code: 'HR', name: 'Croatia', flag: '🇭🇷', cities: ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar', 'Dubrovnik', 'Pula', 'Šibenik', 'Slavonski Brod', 'Karlovac', 'Varaždin', 'Velika Gorica', 'Sisak', 'Vukovar', 'Bjelovar', 'Vinkovci', 'Koprivnica', 'Čakovec', 'Požega', 'Virovitica', 'Đakovo', 'Knin', 'Makarska', 'Rovinj', 'Poreč', 'Opatija', 'Samobor', 'Trogir', 'Hvar', 'Korčula', 'Omiš', 'Senj', 'Crikvenica', 'Biograd na Moru', 'Gospić', 'Kutina', 'Zaprešić', 'Dugo Selo', 'Ivanić-Grad', 'Jastrebarsko', 'Sveti Ivan Zelina', 'Vrbovec', 'Križevci', 'Ludbreg', 'Novska', 'Pakrac', 'Daruvar', 'Slatina', 'Našice', 'Županja', 'Petrinja', 'Glina', 'Duga Resa', 'Ogulin', 'Delnice', 'Pazin', 'Labin', 'Umag', 'Novigrad', 'Buzet', 'Sinj', 'Imotski', 'Metković', 'Ploče', 'Vrgorac', 'Trilj', 'Solin', 'Kaštela', 'Supetar', 'Bol', 'Vis', 'Vodice', 'Primošten', 'Nin', 'Novalja', 'Pag', 'Mali Lošinj', 'Krk', 'Bakar', 'Kraljevica', 'Novi Vinodolski', 'Otočac', 'Slunj', 'Vrlika', 'Drniš', 'Skradin', 'Obrovac', 'Benkovac', 'Gračac', 'Donji Lapac', 'Stari Grad', 'Jelsa', 'Vrboska', 'Komiža', 'Lastovo', 'Blato', 'Vela Luka', 'Orebić', 'Ston', 'Cavtat', 'Konavle', 'Župa Dubrovačka', 'Čilipi'] },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺', cities: ['Havana', 'Santiago de Cuba', 'Camagüey', 'Holguín', 'Santa Clara', 'Varadero'] },
  { code: 'CY', name: 'Cyprus', flag: '🇨🇾', cities: ['Nicosia', 'Limassol', 'Larnaca', 'Paphos', 'Famagusta'] },
  { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿', cities: ['Prague', 'Brno', 'Ostrava', 'Plzeň', 'Liberec', 'Olomouc'] },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰', cities: ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Esbjerg', 'Randers'] },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯', cities: ['Djibouti City', 'Ali Sabieh', 'Tadjoura', 'Obock', 'Dikhil'] },
  { code: 'DM', name: 'Dominica', flag: '🇩🇲', cities: ['Roseau', 'Portsmouth', 'Marigot', 'Berekua', 'Mahaut'] },
  { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴', cities: ['Santo Domingo', 'Santiago', 'La Romana', 'San Pedro de Macorís', 'Puerto Plata', 'Punta Cana'] },
  { code: 'EC', name: 'Ecuador', flag: '🇪🇨', cities: ['Quito', 'Guayaquil', 'Cuenca', 'Santo Domingo', 'Machala', 'Manta'] },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬', cities: ['Cairo', 'Alexandria', 'Giza', 'Sharm El Sheikh', 'Luxor', 'Aswan', 'Hurghada'] },
  { code: 'SV', name: 'El Salvador', flag: '🇸🇻', cities: ['San Salvador', 'Santa Ana', 'San Miguel', 'Mejicanos', 'Soyapango'] },
  { code: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶', cities: ['Malabo', 'Bata', 'Ebebiyin', 'Aconibe', 'Luba'] },
  { code: 'ER', name: 'Eritrea', flag: '🇪🇷', cities: ['Asmara', 'Keren', 'Massawa', 'Assab', 'Mendefera'] },
  { code: 'EE', name: 'Estonia', flag: '🇪🇪', cities: ['Tallinn', 'Tartu', 'Narva', 'Pärnu', 'Kohtla-Järve'] },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿', cities: ['Mbabane', 'Manzini', 'Lobamba', 'Siteki', 'Piggs Peak'] },
  { code: 'ET', name: 'Ethiopia', flag: '🇪🇹', cities: ['Addis Ababa', 'Dire Dawa', 'Mekelle', 'Gondar', 'Hawassa', 'Bahir Dar'] },
  { code: 'FJ', name: 'Fiji', flag: '🇫🇯', cities: ['Suva', 'Nadi', 'Lautoka', 'Labasa', 'Ba'] },
  { code: 'FI', name: 'Finland', flag: '🇫🇮', cities: ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu', 'Turku', 'Rovaniemi'] },
  { code: 'FR', name: 'France', flag: '🇫🇷', cities: ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille'] },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦', cities: ['Libreville', 'Port-Gentil', 'Franceville', 'Oyem', 'Moanda'] },
  { code: 'GM', name: 'Gambia', flag: '🇬🇲', cities: ['Banjul', 'Serekunda', 'Brikama', 'Bakau', 'Farafenni'] },
  { code: 'GE', name: 'Georgia', flag: '🇬🇪', cities: ['Tbilisi', 'Batumi', 'Kutaisi', 'Rustavi', 'Zugdidi'] },
  { code: 'DE', name: 'Germany', flag: '🇩🇪', cities: ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Stuttgart', 'Düsseldorf', 'Dortmund', 'Dresden', 'Leipzig', 'Nuremberg'] },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭', cities: ['Accra', 'Kumasi', 'Tamale', 'Sekondi-Takoradi', 'Cape Coast'] },
  { code: 'GR', name: 'Greece', flag: '🇬🇷', cities: ['Athens', 'Thessaloniki', 'Patras', 'Heraklion', 'Larissa', 'Rhodes', 'Santorini'] },
  { code: 'GD', name: 'Grenada', flag: '🇬🇩', cities: ["St. George's", 'Gouyave', 'Grenville', 'Victoria', 'Sauteurs'] },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹', cities: ['Guatemala City', 'Mixco', 'Villa Nueva', 'Quetzaltenango', 'Antigua Guatemala'] },
  { code: 'GN', name: 'Guinea', flag: '🇬🇳', cities: ['Conakry', 'Nzérékoré', 'Kankan', 'Kindia', 'Labé'] },
  { code: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼', cities: ['Bissau', 'Bafatá', 'Gabú', 'Bissorã', 'Bolama'] },
  { code: 'GY', name: 'Guyana', flag: '🇬🇾', cities: ['Georgetown', 'Linden', 'New Amsterdam', 'Anna Regina', 'Bartica'] },
  { code: 'HT', name: 'Haiti', flag: '🇭🇹', cities: ['Port-au-Prince', 'Cap-Haïtien', 'Gonaïves', 'Les Cayes', 'Jacmel'] },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳', cities: ['Tegucigalpa', 'San Pedro Sula', 'Choloma', 'La Ceiba', 'El Progreso'] },
  { code: 'HU', name: 'Hungary', flag: '🇭🇺', cities: ['Budapest', 'Debrecen', 'Szeged', 'Miskolc', 'Pécs', 'Győr'] },
  { code: 'IS', name: 'Iceland', flag: '🇮🇸', cities: ['Reykjavik', 'Kópavogur', 'Hafnarfjörður', 'Akureyri', 'Keflavík'] },
  { code: 'IN', name: 'India', flag: '🇮🇳', cities: ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata', 'Ahmedabad', 'Pune', 'Jaipur', 'Lucknow', 'Surat'] },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩', cities: ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Semarang', 'Makassar', 'Denpasar', 'Yogyakarta'] },
  { code: 'IR', name: 'Iran', flag: '🇮🇷', cities: ['Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Shiraz', 'Tabriz'] },
  { code: 'IQ', name: 'Iraq', flag: '🇮🇶', cities: ['Baghdad', 'Basra', 'Mosul', 'Erbil', 'Kirkuk', 'Sulaymaniyah'] },
  { code: 'IE', name: 'Ireland', flag: '🇮🇪', cities: ['Dublin', 'Cork', 'Galway', 'Limerick', 'Waterford', 'Kilkenny'] },
  { code: 'IL', name: 'Israel', flag: '🇮🇱', cities: ['Tel Aviv', 'Jerusalem', 'Haifa', 'Rishon LeZion', 'Petah Tikva', 'Eilat'] },
  { code: 'IT', name: 'Italy', flag: '🇮🇹', cities: ['Rome', 'Milan', 'Naples', 'Turin', 'Florence', 'Venice', 'Bologna', 'Genoa', 'Palermo', 'Verona'] },
  { code: 'JM', name: 'Jamaica', flag: '🇯🇲', cities: ['Kingston', 'Montego Bay', 'Spanish Town', 'Portmore', 'Ocho Rios'] },
  { code: 'JP', name: 'Japan', flag: '🇯🇵', cities: ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya', 'Sapporo', 'Fukuoka', 'Kyoto', 'Kobe', 'Hiroshima', 'Sendai'] },
  { code: 'JO', name: 'Jordan', flag: '🇯🇴', cities: ['Amman', 'Zarqa', 'Irbid', 'Aqaba', 'Madaba', 'Petra'] },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', cities: ['Almaty', 'Astana', 'Shymkent', 'Karaganda', 'Aktobe'] },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', cities: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret', 'Malindi'] },
  { code: 'KI', name: 'Kiribati', flag: '🇰🇮', cities: ['Tarawa', 'Betio', 'Bikenibeu', 'Bairiki'] },
  { code: 'KP', name: 'North Korea', flag: '🇰🇵', cities: ['Pyongyang', 'Hamhung', 'Chongjin', 'Nampo', 'Wonsan'] },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷', cities: ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Suwon', 'Ulsan', 'Jeju'] },
  { code: 'KW', name: 'Kuwait', flag: '🇰🇼', cities: ['Kuwait City', 'Hawalli', 'Salmiya', 'Jahra', 'Farwaniya'] },
  { code: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬', cities: ['Bishkek', 'Osh', 'Jalal-Abad', 'Karakol', 'Tokmok'] },
  { code: 'LA', name: 'Laos', flag: '🇱🇦', cities: ['Vientiane', 'Luang Prabang', 'Pakse', 'Savannakhet', 'Phonsavan'] },
  { code: 'LV', name: 'Latvia', flag: '🇱🇻', cities: ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava', 'Jūrmala'] },
  { code: 'LB', name: 'Lebanon', flag: '🇱🇧', cities: ['Beirut', 'Tripoli', 'Sidon', 'Tyre', 'Byblos', 'Jounieh'] },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸', cities: ['Maseru', 'Teyateyaneng', 'Mafeteng', 'Leribe', 'Mohales Hoek'] },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷', cities: ['Monrovia', 'Gbarnga', 'Kakata', 'Bensonville', 'Harper'] },
  { code: 'LY', name: 'Libya', flag: '🇱🇾', cities: ['Tripoli', 'Benghazi', 'Misrata', 'Zawiya', 'Tobruk'] },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮', cities: ['Vaduz', 'Schaan', 'Triesen', 'Balzers', 'Eschen'] },
  { code: 'LT', name: 'Lithuania', flag: '🇱🇹', cities: ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai', 'Panevėžys'] },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺', cities: ['Luxembourg City', 'Esch-sur-Alzette', 'Differdange', 'Dudelange', 'Ettelbruck'] },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬', cities: ['Antananarivo', 'Toamasina', 'Antsirabe', 'Mahajanga', 'Fianarantsoa'] },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼', cities: ['Lilongwe', 'Blantyre', 'Mzuzu', 'Zomba', 'Kasungu'] },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾', cities: ['Kuala Lumpur', 'George Town', 'Johor Bahru', 'Ipoh', 'Shah Alam', 'Petaling Jaya', 'Kota Kinabalu', 'Kuching'] },
  { code: 'MV', name: 'Maldives', flag: '🇲🇻', cities: ['Malé', 'Addu City', 'Fuvahmulah', 'Kulhudhuffushi', 'Thinadhoo'] },
  { code: 'ML', name: 'Mali', flag: '🇲🇱', cities: ['Bamako', 'Sikasso', 'Mopti', 'Ségou', 'Kayes', 'Timbuktu'] },
  { code: 'MT', name: 'Malta', flag: '🇲🇹', cities: ['Valletta', 'Birkirkara', 'Mosta', 'Qormi', 'Sliema', 'St. Julians'] },
  { code: 'MH', name: 'Marshall Islands', flag: '🇲🇭', cities: ['Majuro', 'Ebeye', 'Arno', 'Jabor', 'Wotje'] },
  { code: 'MR', name: 'Mauritania', flag: '🇲🇷', cities: ['Nouakchott', 'Nouadhibou', 'Néma', 'Kaédi', 'Rosso'] },
  { code: 'MU', name: 'Mauritius', flag: '🇲🇺', cities: ['Port Louis', 'Beau Bassin-Rose Hill', 'Vacoas-Phoenix', 'Curepipe', 'Quatre Bornes'] },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽', cities: ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'Cancún', 'Mérida', 'León', 'Querétaro'] },
  { code: 'FM', name: 'Micronesia', flag: '🇫🇲', cities: ['Palikir', 'Weno', 'Kolonia', 'Tofol', 'Colonia'] },
  { code: 'MD', name: 'Moldova', flag: '🇲🇩', cities: ['Chișinău', 'Tiraspol', 'Bălți', 'Bender', 'Rîbnița'] },
  { code: 'MC', name: 'Monaco', flag: '🇲🇨', cities: ['Monaco', 'Monte Carlo', 'La Condamine', 'Fontvieille', 'Moneghetti'] },
  { code: 'MN', name: 'Mongolia', flag: '🇲🇳', cities: ['Ulaanbaatar', 'Erdenet', 'Darkhan', 'Choibalsan', 'Mörön'] },
  { code: 'ME', name: 'Montenegro', flag: '🇲🇪', cities: ['Podgorica', 'Nikšić', 'Pljevlja', 'Bijelo Polje', 'Budva', 'Kotor'] },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦', cities: ['Casablanca', 'Rabat', 'Marrakech', 'Fes', 'Tangier', 'Agadir', 'Meknes'] },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿', cities: ['Maputo', 'Matola', 'Beira', 'Nampula', 'Chimoio'] },
  { code: 'MM', name: 'Myanmar', flag: '🇲🇲', cities: ['Yangon', 'Mandalay', 'Naypyidaw', 'Mawlamyine', 'Bago'] },
  { code: 'NA', name: 'Namibia', flag: '🇳🇦', cities: ['Windhoek', 'Walvis Bay', 'Swakopmund', 'Rundu', 'Oshakati'] },
  { code: 'NR', name: 'Nauru', flag: '🇳🇷', cities: ['Yaren', 'Denigomodu', 'Meneng', 'Aiwo', 'Boe'] },
  { code: 'NP', name: 'Nepal', flag: '🇳🇵', cities: ['Kathmandu', 'Pokhara', 'Lalitpur', 'Bharatpur', 'Biratnagar'] },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱', cities: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Tilburg', 'Groningen'] },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿', cities: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga', 'Dunedin', 'Queenstown'] },
  { code: 'NI', name: 'Nicaragua', flag: '🇳🇮', cities: ['Managua', 'León', 'Masaya', 'Matagalpa', 'Chinandega'] },
  { code: 'NE', name: 'Niger', flag: '🇳🇪', cities: ['Niamey', 'Zinder', 'Maradi', 'Agadez', 'Tahoua'] },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬', cities: ['Lagos', 'Kano', 'Ibadan', 'Abuja', 'Port Harcourt', 'Benin City', 'Kaduna'] },
  { code: 'MK', name: 'North Macedonia', flag: '🇲🇰', cities: ['Skopje', 'Bitola', 'Kumanovo', 'Prilep', 'Tetovo', 'Ohrid'] },
  { code: 'NO', name: 'Norway', flag: '🇳🇴', cities: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Drammen', 'Tromsø'] },
  { code: 'OM', name: 'Oman', flag: '🇴🇲', cities: ['Muscat', 'Salalah', 'Sohar', 'Nizwa', 'Sur'] },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰', cities: ['Karachi', 'Lahore', 'Faisalabad', 'Rawalpindi', 'Islamabad', 'Multan', 'Peshawar'] },
  { code: 'PW', name: 'Palau', flag: '🇵🇼', cities: ['Ngerulmud', 'Koror', 'Meyungs', 'Airai', 'Kloulklubed'] },
  { code: 'PS', name: 'Palestine', flag: '🇵🇸', cities: ['Gaza City', 'Ramallah', 'Hebron', 'Nablus', 'Bethlehem'] },
  { code: 'PA', name: 'Panama', flag: '🇵🇦', cities: ['Panama City', 'San Miguelito', 'Tocumen', 'David', 'Colón'] },
  { code: 'PG', name: 'Papua New Guinea', flag: '🇵🇬', cities: ['Port Moresby', 'Lae', 'Mount Hagen', 'Madang', 'Wewak'] },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾', cities: ['Asunción', 'Ciudad del Este', 'San Lorenzo', 'Luque', 'Capiatá'] },
  { code: 'PE', name: 'Peru', flag: '🇵🇪', cities: ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Cusco', 'Piura'] },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭', cities: ['Manila', 'Quezon City', 'Davao City', 'Cebu City', 'Zamboanga', 'Makati', 'Pasig'] },
  { code: 'PL', name: 'Poland', flag: '🇵🇱', cities: ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Poznań', 'Gdańsk', 'Szczecin', 'Katowice'] },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹', cities: ['Lisbon', 'Porto', 'Amadora', 'Braga', 'Setúbal', 'Coimbra', 'Faro'] },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦', cities: ['Doha', 'Al Rayyan', 'Al Wakrah', 'Al Khor', 'Umm Salal'] },
  { code: 'RO', name: 'Romania', flag: '🇷🇴', cities: ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța', 'Craiova', 'Brașov'] },
  { code: 'RU', name: 'Russia', flag: '🇷🇺', cities: ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Kazan', 'Nizhny Novgorod', 'Chelyabinsk', 'Samara', 'Sochi'] },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼', cities: ['Kigali', 'Butare', 'Gitarama', 'Ruhengeri', 'Gisenyi'] },
  { code: 'KN', name: 'Saint Kitts and Nevis', flag: '🇰🇳', cities: ['Basseterre', 'Charlestown', 'Sandy Point Town', 'Dieppe Bay Town'] },
  { code: 'LC', name: 'Saint Lucia', flag: '🇱🇨', cities: ['Castries', 'Vieux Fort', 'Micoud', 'Soufrière', 'Dennery'] },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨', cities: ['Kingstown', 'Georgetown', 'Byera Village', 'Biabou', 'Barrouallie'] },
  { code: 'WS', name: 'Samoa', flag: '🇼🇸', cities: ['Apia', 'Vaitele', 'Faleula', 'Siusega', 'Malie'] },
  { code: 'SM', name: 'San Marino', flag: '🇸🇲', cities: ['San Marino', 'Serravalle', 'Borgo Maggiore', 'Domagnano', 'Fiorentino'] },
  { code: 'ST', name: 'Sao Tome and Principe', flag: '🇸🇹', cities: ['São Tomé', 'Santo António', 'Neves', 'Santana', 'Trindade'] },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', cities: ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam', 'Khobar', 'Tabuk'] },
  { code: 'SN', name: 'Senegal', flag: '🇸🇳', cities: ['Dakar', 'Touba', 'Thiès', 'Rufisque', 'Saint-Louis'] },
  { code: 'RS', name: 'Serbia', flag: '🇷🇸', cities: ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac', 'Subotica'] },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨', cities: ['Victoria', 'Anse Boileau', 'Beau Vallon', 'Anse Royale', 'Cascade'] },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱', cities: ['Freetown', 'Bo', 'Kenema', 'Makeni', 'Koidu'] },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬', cities: ['Singapore', 'Woodlands', 'Tampines', 'Jurong East', 'Changi'] },
  { code: 'SK', name: 'Slovakia', flag: '🇸🇰', cities: ['Bratislava', 'Košice', 'Prešov', 'Žilina', 'Nitra', 'Banská Bystrica'] },
  { code: 'SI', name: 'Slovenia', flag: '🇸🇮', cities: ['Ljubljana', 'Maribor', 'Celje', 'Kranj', 'Velenje', 'Koper'] },
  { code: 'SB', name: 'Solomon Islands', flag: '🇸🇧', cities: ['Honiara', 'Auki', 'Gizo', 'Buala', 'Tulagi'] },
  { code: 'SO', name: 'Somalia', flag: '🇸🇴', cities: ['Mogadishu', 'Hargeisa', 'Kismayo', 'Marka', 'Berbera'] },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦', cities: ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth', 'Bloemfontein', 'Soweto'] },
  { code: 'SS', name: 'South Sudan', flag: '🇸🇸', cities: ['Juba', 'Wau', 'Malakal', 'Yei', 'Bor'] },
  { code: 'ES', name: 'Spain', flag: '🇪🇸', cities: ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Málaga', 'Bilbao', 'Alicante', 'Palma de Mallorca'] },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', cities: ['Colombo', 'Kandy', 'Galle', 'Jaffna', 'Negombo', 'Trincomalee'] },
  { code: 'SD', name: 'Sudan', flag: '🇸🇩', cities: ['Khartoum', 'Omdurman', 'Port Sudan', 'Kassala', 'El Obeid'] },
  { code: 'SR', name: 'Suriname', flag: '🇸🇷', cities: ['Paramaribo', 'Lelydorp', 'Nieuw Nickerie', 'Moengo', 'Nieuw Amsterdam'] },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪', cities: ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Västerås', 'Örebro', 'Linköping'] },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭', cities: ['Zürich', 'Geneva', 'Basel', 'Lausanne', 'Bern', 'Winterthur', 'Lucerne'] },
  { code: 'SY', name: 'Syria', flag: '🇸🇾', cities: ['Damascus', 'Aleppo', 'Homs', 'Latakia', 'Hama', 'Tartus'] },
  { code: 'TW', name: 'Taiwan', flag: '🇹🇼', cities: ['Taipei', 'Kaohsiung', 'Taichung', 'Tainan', 'Hsinchu', 'Taoyuan'] },
  { code: 'TJ', name: 'Tajikistan', flag: '🇹🇯', cities: ['Dushanbe', 'Khujand', 'Bokhtar', 'Kulob', 'Istaravshan'] },
  { code: 'TZ', name: 'Tanzania', flag: '🇹🇿', cities: ['Dar es Salaam', 'Mwanza', 'Arusha', 'Dodoma', 'Mbeya', 'Zanzibar City'] },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭', cities: ['Bangkok', 'Chiang Mai', 'Pattaya', 'Phuket', 'Nonthaburi', 'Hat Yai', 'Udon Thani'] },
  { code: 'TL', name: 'Timor-Leste', flag: '🇹🇱', cities: ['Dili', 'Baucau', 'Maliana', 'Suai', 'Lospalos'] },
  { code: 'TG', name: 'Togo', flag: '🇹🇬', cities: ['Lomé', 'Sokodé', 'Kara', 'Kpalimé', 'Atakpamé'] },
  { code: 'TO', name: 'Tonga', flag: '🇹🇴', cities: ["Nuku'alofa", 'Neiafu', 'Haveluloto', 'Vaini', 'Pangai'] },
  { code: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹', cities: ['Port of Spain', 'San Fernando', 'Chaguanas', 'Arima', 'Scarborough'] },
  { code: 'TN', name: 'Tunisia', flag: '🇹🇳', cities: ['Tunis', 'Sfax', 'Sousse', 'Kairouan', 'Bizerte', 'Gabès'] },
  { code: 'TR', name: 'Turkey', flag: '🇹🇷', cities: ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya', 'Adana', 'Konya', 'Gaziantep'] },
  { code: 'TM', name: 'Turkmenistan', flag: '🇹🇲', cities: ['Ashgabat', 'Türkmenabat', 'Daşoguz', 'Mary', 'Balkanabat'] },
  { code: 'TV', name: 'Tuvalu', flag: '🇹🇻', cities: ['Funafuti', 'Vaiaku', 'Asau', 'Savave', 'Tanrake'] },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬', cities: ['Kampala', 'Gulu', 'Lira', 'Mbarara', 'Jinja', 'Entebbe'] },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦', cities: ['Kyiv', 'Kharkiv', 'Odessa', 'Dnipro', 'Donetsk', 'Zaporizhzhia', 'Lviv'] },
  { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪', cities: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman', 'Al Ain', 'Ras Al Khaimah', 'Fujairah'] },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', cities: ['London', 'Birmingham', 'Manchester', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh', 'Bristol', 'Sheffield', 'Cardiff'] },
  { code: 'US', name: 'United States', flag: '🇺🇸', cities: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Austin', 'Jacksonville', 'San Francisco', 'Seattle', 'Denver', 'Boston', 'Miami', 'Atlanta', 'Las Vegas', 'Detroit'] },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾', cities: ['Montevideo', 'Salto', 'Ciudad de la Costa', 'Paysandú', 'Las Piedras'] },
  { code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿', cities: ['Tashkent', 'Samarkand', 'Namangan', 'Andijan', 'Bukhara'] },
  { code: 'VU', name: 'Vanuatu', flag: '🇻🇺', cities: ['Port Vila', 'Luganville', 'Norsup', 'Port Olry', 'Lakatoro'] },
  { code: 'VA', name: 'Vatican City', flag: '🇻🇦', cities: ['Vatican City'] },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪', cities: ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 'Maracay', 'Ciudad Guayana'] },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳', cities: ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Haiphong', 'Can Tho', 'Nha Trang', 'Hue'] },
  { code: 'YE', name: 'Yemen', flag: '🇾🇪', cities: ["Sana'a", 'Aden', 'Taiz', 'Al Hudaydah', 'Ibb'] },
  { code: 'ZM', name: 'Zambia', flag: '🇿🇲', cities: ['Lusaka', 'Kitwe', 'Ndola', 'Kabwe', 'Chingola', 'Livingstone'] },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', cities: ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare', 'Gweru', 'Victoria Falls'] },
];

export const getCountryByCode = (code: string): Country | undefined => {
  return COUNTRIES.find((c) => c.code === code);
};

export const getCountryDisplayName = (code: string): string => {
  const country = getCountryByCode(code);
  return country ? `${country.flag} ${country.name}` : '';
};

export const getCitiesForCountry = (countryCode: string): string[] => {
  const country = getCountryByCode(countryCode);
  return country?.cities.slice().sort((a, b) => a.localeCompare(b)) || [];
};
